project '171226_AlamofireTest.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '171226_AlamofireTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 171226_AlamofireTest
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Socket.IO-Client-Swift'
end
