# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '17-11-20-Creat-Instagram' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 17-11-20-Creat-Instagram

  pod 'Firebase'
  pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Database'
end
